export const labStudies = [
  { nombre: 'Hemograma completo', categoria: 'Hematología' },
  { nombre: 'Glucemia en ayunas', categoria: 'Bioquímica' },
  { nombre: 'Glucemia postprandial', categoria: 'Bioquímica' },
  { nombre: 'Hemoglobina glicosilada (HbA1c)', categoria: 'Bioquímica' },
  { nombre: 'Perfil lipídico', categoria: 'Bioquímica' },
  { nombre: 'Colesterol total', categoria: 'Bioquímica' },
  { nombre: 'Colesterol HDL', categoria: 'Bioquímica' },
  { nombre: 'Colesterol LDL', categoria: 'Bioquímica' },
  { nombre: 'Triglicéridos', categoria: 'Bioquímica' },
  { nombre: 'Urea', categoria: 'Bioquímica' },
  { nombre: 'Creatinina', categoria: 'Bioquímica' },
  { nombre: 'Ácido úrico', categoria: 'Bioquímica' },
  { nombre: 'Transaminasas (GOT/GPT)', categoria: 'Bioquímica' },
  { nombre: 'Gamma GT', categoria: 'Bioquímica' },
  { nombre: 'Bilirrubinas', categoria: 'Bioquímica' },
  { nombre: 'Fosfatasa alcalina', categoria: 'Bioquímica' },
  { nombre: 'Proteínas totales', categoria: 'Bioquímica' },
  { nombre: 'TSH', categoria: 'Endocrinología' },
  { nombre: 'T4 libre', categoria: 'Endocrinología' },
  { nombre: 'T3 total', categoria: 'Endocrinología' },
  { nombre: 'Potasio', categoria: 'Electrolitos' },
  { nombre: 'Sodio', categoria: 'Electrolitos' },
  { nombre: 'Calcio', categoria: 'Electrolitos' },
  { nombre: 'Examen general de orina', categoria: 'Uroanálisis' },
  { nombre: 'Urocultivo', categoria: 'Microbiología' },
  { nombre: 'Hemocultivo', categoria: 'Microbiología' },
  { nombre: 'Coproparasitológico', categoria: 'Microbiología' },
  { nombre: 'VDRL', categoria: 'Serología' },
  { nombre: 'VIH (Elisa)', categoria: 'Serología' },
  { nombre: 'Antígeno prostático (PSA)', categoria: 'Endocrinología' },
  { nombre: 'Proteína C reactiva', categoria: 'Inmunología' },
  { nombre: 'VDRL', categoria: 'Serología' },
  { nombre: 'Grupo sanguíneo y factor Rh', categoria: 'Hematología' },
  { nombre: 'Tiempo de protrombina (TP)', categoria: 'Coagulación' },
  { nombre: 'Tiempo de tromboplastina parcial (TPT)', categoria: 'Coagulación' },
];

export const imagingStudies = [
  { nombre: 'Radiografía de tórax', categoria: 'Radiología' },
  { nombre: 'Radiografía de abdomen', categoria: 'Radiología' },
  { nombre: 'Radiografía de columna lumbar', categoria: 'Radiología' },
  { nombre: 'Radiografía de columna cervical', categoria: 'Radiología' },
  { nombre: 'Radiografía de extremidades', categoria: 'Radiología' },
  { nombre: 'Ecografía abdominal', categoria: 'Ecografía' },
  { nombre: 'Ecografía pélvica', categoria: 'Ecografía' },
  { nombre: 'Ecografía obstétrica', categoria: 'Ecografía' },
  { nombre: 'Ecografía de tiroides', categoria: 'Ecografía' },
  { nombre: 'Ecografía renal', categoria: 'Ecografía' },
  { nombre: 'Ecocardiograma', categoria: 'Ecografía' },
  { nombre: 'Tomografía axial computarizada (TAC) de cráneo', categoria: 'TAC' },
  { nombre: 'TAC de abdomen', categoria: 'TAC' },
  { nombre: 'TAC de tórax', categoria: 'TAC' },
  { nombre: 'Resonancia magnética de cráneo', categoria: 'RMN' },
  { nombre: 'Resonancia magnética de columna', categoria: 'RMN' },
  { nombre: 'Mamografía', categoria: 'Radiología' },
  { nombre: 'Electrocardiograma (ECG)', categoria: 'Cardiología' },
];